// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bd_0_v_hscaler_0_v_hscaler_AXIvideo2MultiPixStream83 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_axis_video_TDATA,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        img_V_val_V_din,
        img_V_val_V_full_n,
        img_V_val_V_write,
        Height,
        WidthIn,
        colorMode,
        HwReg_WidthOut,
        Height_out_din,
        Height_out_full_n,
        Height_out_write,
        WidthIn_out_din,
        WidthIn_out_full_n,
        WidthIn_out_write,
        colorMode_out_din,
        colorMode_out_full_n,
        colorMode_out_write,
        HwReg_WidthOut_out_din,
        HwReg_WidthOut_out_full_n,
        HwReg_WidthOut_out_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 7'b1;
parameter    ap_ST_st2_fsm_1 = 7'b10;
parameter    ap_ST_st3_fsm_2 = 7'b100;
parameter    ap_ST_st4_fsm_3 = 7'b1000;
parameter    ap_ST_pp1_stg0_fsm_4 = 7'b10000;
parameter    ap_ST_st7_fsm_5 = 7'b100000;
parameter    ap_ST_st8_fsm_6 = 7'b1000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] s_axis_video_TDATA;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input  [2:0] s_axis_video_TKEEP;
input  [2:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
output  [23:0] img_V_val_V_din;
input   img_V_val_V_full_n;
output   img_V_val_V_write;
input  [15:0] Height;
input  [15:0] WidthIn;
input  [7:0] colorMode;
input  [15:0] HwReg_WidthOut;
output  [15:0] Height_out_din;
input   Height_out_full_n;
output   Height_out_write;
output  [15:0] WidthIn_out_din;
input   WidthIn_out_full_n;
output   WidthIn_out_write;
output  [7:0] colorMode_out_din;
input   colorMode_out_full_n;
output   colorMode_out_write;
output  [15:0] HwReg_WidthOut_out_din;
input   HwReg_WidthOut_out_full_n;
output   HwReg_WidthOut_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg s_axis_video_TREADY;
reg img_V_val_V_write;
reg Height_out_write;
reg WidthIn_out_write;
reg colorMode_out_write;
reg HwReg_WidthOut_out_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm = 7'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_26;
reg   [0:0] eol_reg_222;
reg   [23:0] axi_data_V_1_i_i_reg_233;
reg   [0:0] eol_i_i_reg_244;
reg   [11:0] j_i_i_reg_256;
reg   [0:0] axi_last_V_2_i_i_reg_267;
reg   [23:0] p_Val2_s_reg_280;
reg    ap_sig_bdd_91;
wire   [12:0] tmp_fu_336_p1;
reg   [12:0] tmp_reg_464;
reg   [23:0] tmp_data_V_reg_469;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_105;
reg   [0:0] tmp_last_V_reg_477;
wire   [12:0] tmp_34_fu_344_p1;
reg   [12:0] tmp_34_reg_489;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_119;
wire   [0:0] sel_tmp2_fu_347_p2;
reg   [0:0] sel_tmp2_reg_494;
wire   [0:0] exitcond_i_i_fu_361_p2;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_130;
wire   [11:0] i_fu_366_p2;
reg   [11:0] i_reg_505;
wire   [0:0] exitcond2_i_i_fu_376_p2;
reg   [0:0] exitcond2_i_i_reg_510;
reg    ap_sig_cseq_ST_pp1_stg0_fsm_4;
reg    ap_sig_bdd_141;
wire   [0:0] brmerge_i_i_fu_390_p2;
reg    ap_sig_bdd_149;
reg    ap_reg_ppiten_pp1_it0 = 1'b0;
reg    ap_sig_bdd_156;
reg    ap_reg_ppiten_pp1_it1 = 1'b0;
wire   [11:0] j_fu_381_p2;
wire   [7:0] pix_val_0_V_2_fu_410_p3;
reg   [7:0] pix_val_0_V_2_reg_523;
wire   [7:0] pix_val_1_V_1_fu_427_p3;
reg   [7:0] pix_val_1_V_1_reg_528;
wire   [7:0] pix_val_2_V_1_fu_434_p3;
reg   [7:0] pix_val_2_V_1_reg_533;
reg    ap_sig_cseq_ST_st7_fsm_5;
reg    ap_sig_bdd_181;
reg    ap_sig_bdd_186;
reg   [0:0] axi_last_V1_i_i_reg_191;
reg   [0:0] axi_last_V_3_i_i_reg_292;
reg    ap_sig_cseq_ST_st8_fsm_6;
reg    ap_sig_bdd_204;
reg   [23:0] axi_data_V1_i_i_reg_201;
reg   [23:0] axi_data_V_3_i_i_reg_304;
reg   [11:0] i_i_i_reg_211;
reg   [0:0] eol_phi_fu_225_p4;
reg   [23:0] axi_data_V_1_i_i_phi_fu_236_p4;
reg   [0:0] eol_i_i_phi_fu_248_p4;
wire   [0:0] ap_reg_phiprechg_axi_last_V_2_i_i_reg_267pp1_it0;
wire   [23:0] ap_reg_phiprechg_p_Val2_s_reg_280pp1_it0;
reg   [23:0] p_Val2_s_phi_fu_284_p4;
reg   [0:0] eol_2_i_i_reg_316;
reg   [0:0] sof_1_i_i_fu_106;
wire   [12:0] i_cast_i_i_fu_357_p1;
wire   [12:0] j_cast_i_i_fu_372_p1;
wire   [7:0] pix_val_0_V_fu_396_p4;
wire   [7:0] pix_val_1_V_2_fu_406_p1;
wire   [7:0] pix_val_2_V_fu_417_p4;
wire   [0:0] tmp_user_V_fu_340_p1;
reg   [6:0] ap_NS_fsm;
reg    ap_sig_bdd_148;
reg    ap_sig_bdd_227;
reg    ap_sig_bdd_167;
reg    ap_sig_bdd_247;




always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(exitcond_i_i_fu_361_p2 == ap_const_lv1_0))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp1_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond2_i_i_fu_376_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond_i_i_fu_361_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp1_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_i_i_fu_376_p2 == ap_const_lv1_0) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond_i_i_fu_361_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond2_i_i_fu_376_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        axi_data_V1_i_i_reg_201 <= axi_data_V_3_i_i_reg_304;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        axi_data_V1_i_i_reg_201 <= tmp_data_V_reg_469;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_i_i_reg_510 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        axi_data_V_1_i_i_reg_233 <= p_Val2_s_reg_280;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond_i_i_fu_361_p2 == ap_const_lv1_0))) begin
        axi_data_V_1_i_i_reg_233 <= axi_data_V1_i_i_reg_201;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond2_i_i_fu_376_p2 == ap_const_lv1_0))) begin
        axi_data_V_3_i_i_reg_304 <= axi_data_V_1_i_i_phi_fu_236_p4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_2_i_i_reg_316) & ~ap_sig_bdd_186)) begin
        axi_data_V_3_i_i_reg_304 <= s_axis_video_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        axi_last_V1_i_i_reg_191 <= axi_last_V_3_i_i_reg_292;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        axi_last_V1_i_i_reg_191 <= tmp_last_V_reg_477;
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_bdd_167) begin
        if (ap_sig_bdd_227) begin
            axi_last_V_2_i_i_reg_267 <= eol_phi_fu_225_p4;
        end else if (ap_sig_bdd_148) begin
            axi_last_V_2_i_i_reg_267 <= s_axis_video_TLAST;
        end else if ((ap_true == ap_true)) begin
            axi_last_V_2_i_i_reg_267 <= ap_reg_phiprechg_axi_last_V_2_i_i_reg_267pp1_it0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond2_i_i_fu_376_p2 == ap_const_lv1_0))) begin
        axi_last_V_3_i_i_reg_292 <= eol_phi_fu_225_p4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_2_i_i_reg_316) & ~ap_sig_bdd_186)) begin
        axi_last_V_3_i_i_reg_292 <= s_axis_video_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond2_i_i_fu_376_p2 == ap_const_lv1_0))) begin
        eol_2_i_i_reg_316 <= eol_i_i_phi_fu_248_p4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_2_i_i_reg_316) & ~ap_sig_bdd_186)) begin
        eol_2_i_i_reg_316 <= s_axis_video_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_i_i_reg_510 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        eol_i_i_reg_244 <= axi_last_V_2_i_i_reg_267;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond_i_i_fu_361_p2 == ap_const_lv1_0))) begin
        eol_i_i_reg_244 <= ap_const_lv1_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_i_i_reg_510 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        eol_reg_222 <= axi_last_V_2_i_i_reg_267;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond_i_i_fu_361_p2 == ap_const_lv1_0))) begin
        eol_reg_222 <= axi_last_V1_i_i_reg_191;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        i_i_i_reg_211 <= i_reg_505;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        i_i_i_reg_211 <= ap_const_lv12_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_i_i_fu_376_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        j_i_i_reg_256 <= j_fu_381_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond_i_i_fu_361_p2 == ap_const_lv1_0))) begin
        j_i_i_reg_256 <= ap_const_lv12_0;
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_bdd_167) begin
        if (ap_sig_bdd_227) begin
            p_Val2_s_reg_280 <= axi_data_V_1_i_i_phi_fu_236_p4;
        end else if (ap_sig_bdd_148) begin
            p_Val2_s_reg_280 <= s_axis_video_TDATA;
        end else if ((ap_true == ap_true)) begin
            p_Val2_s_reg_280 <= ap_reg_phiprechg_p_Val2_s_reg_280pp1_it0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_i_i_fu_376_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        sof_1_i_i_fu_106 <= ap_const_lv1_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        sof_1_i_i_fu_106 <= ap_const_lv1_1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        exitcond2_i_i_reg_510 <= exitcond2_i_i_fu_376_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        i_reg_505 <= i_fu_366_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_i_i_fu_376_p2 == ap_const_lv1_0) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        pix_val_0_V_2_reg_523 <= pix_val_0_V_2_fu_410_p3;
        pix_val_1_V_1_reg_528 <= pix_val_1_V_1_fu_427_p3;
        pix_val_2_V_1_reg_533 <= pix_val_2_V_1_fu_434_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        sel_tmp2_reg_494 <= sel_tmp2_fu_347_p2;
        tmp_34_reg_489 <= tmp_34_fu_344_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(s_axis_video_TVALID == ap_const_logic_0))) begin
        tmp_data_V_reg_469 <= s_axis_video_TDATA;
        tmp_last_V_reg_477 <= s_axis_video_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_91)) begin
        tmp_reg_464 <= tmp_fu_336_p1;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_91) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_91)) begin
        Height_out_write = ap_const_logic_1;
    end else begin
        Height_out_write = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_91) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_91)) begin
        HwReg_WidthOut_out_write = ap_const_logic_1;
    end else begin
        HwReg_WidthOut_out_write = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_91) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_91)) begin
        WidthIn_out_write = ap_const_logic_1;
    end else begin
        WidthIn_out_write = ap_const_logic_0;
    end
end

always @ (ap_done_reg or exitcond_i_i_fu_361_p2 or ap_sig_cseq_ST_st4_fsm_3) begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(exitcond_i_i_fu_361_p2 == ap_const_lv1_0)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (exitcond_i_i_fu_361_p2 or ap_sig_cseq_ST_st4_fsm_3) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(exitcond_i_i_fu_361_p2 == ap_const_lv1_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_141) begin
    if (ap_sig_bdd_141) begin
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_26) begin
    if (ap_sig_bdd_26) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_105) begin
    if (ap_sig_bdd_105) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_119) begin
    if (ap_sig_bdd_119) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_130) begin
    if (ap_sig_bdd_130) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_181) begin
    if (ap_sig_bdd_181) begin
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_204) begin
    if (ap_sig_bdd_204) begin
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_0;
    end
end

always @ (axi_data_V_1_i_i_reg_233 or p_Val2_s_reg_280 or exitcond2_i_i_reg_510 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_i_i_reg_510 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        axi_data_V_1_i_i_phi_fu_236_p4 = p_Val2_s_reg_280;
    end else begin
        axi_data_V_1_i_i_phi_fu_236_p4 = axi_data_V_1_i_i_reg_233;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_91) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_91)) begin
        colorMode_out_write = ap_const_logic_1;
    end else begin
        colorMode_out_write = ap_const_logic_0;
    end
end

always @ (eol_i_i_reg_244 or axi_last_V_2_i_i_reg_267 or exitcond2_i_i_reg_510 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_i_i_reg_510 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        eol_i_i_phi_fu_248_p4 = axi_last_V_2_i_i_reg_267;
    end else begin
        eol_i_i_phi_fu_248_p4 = eol_i_i_reg_244;
    end
end

always @ (eol_reg_222 or axi_last_V_2_i_i_reg_267 or exitcond2_i_i_reg_510 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_i_i_reg_510 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        eol_phi_fu_225_p4 = axi_last_V_2_i_i_reg_267;
    end else begin
        eol_phi_fu_225_p4 = eol_reg_222;
    end
end

always @ (exitcond2_i_i_reg_510 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_sig_bdd_149 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_156 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_i_i_reg_510 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        img_V_val_V_write = ap_const_logic_1;
    end else begin
        img_V_val_V_write = ap_const_logic_0;
    end
end

always @ (s_axis_video_TDATA or brmerge_i_i_fu_390_p2 or axi_data_V_1_i_i_phi_fu_236_p4 or ap_reg_phiprechg_p_Val2_s_reg_280pp1_it0 or ap_sig_bdd_247) begin
    if (ap_sig_bdd_247) begin
        if (~(ap_const_lv1_0 == brmerge_i_i_fu_390_p2)) begin
            p_Val2_s_phi_fu_284_p4 = axi_data_V_1_i_i_phi_fu_236_p4;
        end else if ((ap_const_lv1_0 == brmerge_i_i_fu_390_p2)) begin
            p_Val2_s_phi_fu_284_p4 = s_axis_video_TDATA;
        end else begin
            p_Val2_s_phi_fu_284_p4 = ap_reg_phiprechg_p_Val2_s_reg_280pp1_it0;
        end
    end else begin
        p_Val2_s_phi_fu_284_p4 = ap_reg_phiprechg_p_Val2_s_reg_280pp1_it0;
    end
end

always @ (s_axis_video_TVALID or ap_sig_cseq_ST_st2_fsm_1 or exitcond2_i_i_fu_376_p2 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or brmerge_i_i_fu_390_p2 or ap_sig_bdd_149 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_156 or ap_reg_ppiten_pp1_it1 or ap_sig_cseq_ST_st7_fsm_5 or ap_sig_bdd_186 or eol_2_i_i_reg_316) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(s_axis_video_TVALID == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_2_i_i_reg_316) & ~ap_sig_bdd_186) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_i_i_fu_376_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == brmerge_i_i_fu_390_p2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))))) begin
        s_axis_video_TREADY = ap_const_logic_1;
    end else begin
        s_axis_video_TREADY = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or s_axis_video_TVALID or ap_sig_bdd_91 or exitcond_i_i_fu_361_p2 or exitcond2_i_i_fu_376_p2 or ap_sig_bdd_149 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_156 or ap_reg_ppiten_pp1_it1 or ap_sig_bdd_186 or eol_2_i_i_reg_316 or tmp_user_V_fu_340_p1) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_91) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((~(s_axis_video_TVALID == ap_const_logic_0) & (ap_const_lv1_0 == tmp_user_V_fu_340_p1))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else if ((~(s_axis_video_TVALID == ap_const_logic_0) & ~(ap_const_lv1_0 == tmp_user_V_fu_340_p1))) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            if (~(exitcond_i_i_fu_361_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end
        end
        ap_ST_pp1_stg0_fsm_4 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond2_i_i_fu_376_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond2_i_i_fu_376_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end
        end
        ap_ST_st7_fsm_5 : 
        begin
            if (((ap_const_lv1_0 == eol_2_i_i_reg_316) & ~ap_sig_bdd_186)) begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end else if ((~ap_sig_bdd_186 & ~(ap_const_lv1_0 == eol_2_i_i_reg_316))) begin
                ap_NS_fsm = ap_ST_st8_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end
        end
        ap_ST_st8_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


assign Height_out_din = Height;

assign HwReg_WidthOut_out_din = HwReg_WidthOut;

assign WidthIn_out_din = WidthIn;

assign ap_reg_phiprechg_axi_last_V_2_i_i_reg_267pp1_it0 = 'bx;

assign ap_reg_phiprechg_p_Val2_s_reg_280pp1_it0 = 'bx;


always @ (ap_CS_fsm) begin
    ap_sig_bdd_105 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_119 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_130 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_141 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end


always @ (exitcond2_i_i_fu_376_p2 or brmerge_i_i_fu_390_p2) begin
    ap_sig_bdd_148 = ((exitcond2_i_i_fu_376_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == brmerge_i_i_fu_390_p2));
end


always @ (s_axis_video_TVALID or exitcond2_i_i_fu_376_p2 or brmerge_i_i_fu_390_p2) begin
    ap_sig_bdd_149 = ((s_axis_video_TVALID == ap_const_logic_0) & (exitcond2_i_i_fu_376_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == brmerge_i_i_fu_390_p2));
end


always @ (img_V_val_V_full_n or exitcond2_i_i_reg_510) begin
    ap_sig_bdd_156 = ((img_V_val_V_full_n == ap_const_logic_0) & (exitcond2_i_i_reg_510 == ap_const_lv1_0));
end


always @ (ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_sig_bdd_149 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_156 or ap_reg_ppiten_pp1_it1) begin
    ap_sig_bdd_167 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_149 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_181 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end


always @ (s_axis_video_TVALID or eol_2_i_i_reg_316) begin
    ap_sig_bdd_186 = ((s_axis_video_TVALID == ap_const_logic_0) & (ap_const_lv1_0 == eol_2_i_i_reg_316));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_204 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end


always @ (exitcond2_i_i_fu_376_p2 or brmerge_i_i_fu_390_p2) begin
    ap_sig_bdd_227 = ((exitcond2_i_i_fu_376_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == brmerge_i_i_fu_390_p2));
end


always @ (exitcond2_i_i_fu_376_p2 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it0) begin
    ap_sig_bdd_247 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_i_i_fu_376_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_26 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_start or ap_done_reg or Height_out_full_n or WidthIn_out_full_n or colorMode_out_full_n or HwReg_WidthOut_out_full_n) begin
    ap_sig_bdd_91 = ((Height_out_full_n == ap_const_logic_0) | (WidthIn_out_full_n == ap_const_logic_0) | (colorMode_out_full_n == ap_const_logic_0) | (HwReg_WidthOut_out_full_n == ap_const_logic_0) | (ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

assign brmerge_i_i_fu_390_p2 = (sof_1_i_i_fu_106 | eol_i_i_phi_fu_248_p4);

assign colorMode_out_din = colorMode;

assign exitcond2_i_i_fu_376_p2 = (j_cast_i_i_fu_372_p1 == tmp_reg_464? 1'b1: 1'b0);

assign exitcond_i_i_fu_361_p2 = (i_cast_i_i_fu_357_p1 == tmp_34_reg_489? 1'b1: 1'b0);

assign i_cast_i_i_fu_357_p1 = i_i_i_reg_211;

assign i_fu_366_p2 = (i_i_i_reg_211 + ap_const_lv12_1);

assign img_V_val_V_din = {{{pix_val_2_V_1_reg_533}, {pix_val_1_V_1_reg_528}}, {pix_val_0_V_2_reg_523}};

assign j_cast_i_i_fu_372_p1 = j_i_i_reg_256;

assign j_fu_381_p2 = (j_i_i_reg_256 + ap_const_lv12_1);

assign pix_val_0_V_2_fu_410_p3 = ((sel_tmp2_reg_494[0:0] === 1'b1) ? pix_val_0_V_fu_396_p4 : pix_val_1_V_2_fu_406_p1);

assign pix_val_0_V_fu_396_p4 = {{p_Val2_s_phi_fu_284_p4[ap_const_lv32_17 : ap_const_lv32_10]}};

assign pix_val_1_V_1_fu_427_p3 = ((sel_tmp2_reg_494[0:0] === 1'b1) ? pix_val_1_V_2_fu_406_p1 : pix_val_2_V_fu_417_p4);

assign pix_val_1_V_2_fu_406_p1 = p_Val2_s_phi_fu_284_p4[7:0];

assign pix_val_2_V_1_fu_434_p3 = ((sel_tmp2_reg_494[0:0] === 1'b1) ? pix_val_2_V_fu_417_p4 : pix_val_0_V_fu_396_p4);

assign pix_val_2_V_fu_417_p4 = {{p_Val2_s_phi_fu_284_p4[ap_const_lv32_F : ap_const_lv32_8]}};

assign sel_tmp2_fu_347_p2 = (colorMode == ap_const_lv8_0? 1'b1: 1'b0);

assign tmp_34_fu_344_p1 = Height[12:0];

assign tmp_fu_336_p1 = WidthIn[12:0];

assign tmp_user_V_fu_340_p1 = s_axis_video_TUSER;


endmodule //bd_0_v_hscaler_0_v_hscaler_AXIvideo2MultiPixStream83

