# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/hdmi_final/HW/xdc/scaler_to_vpss_phys.xdc

# XDC: C:/hdmi_final/HW/xdc/scaler_to_vpss_timing.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_iic_0_0 || ORIG_REF_NAME==design_1_axi_iic_0_0}]

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0}]

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0}]

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}]

# IP: bd/design_1/ip/design_1_proc_sys_rst_ctrl_0/design_1_proc_sys_rst_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_rst_ctrl_0 || ORIG_REF_NAME==design_1_proc_sys_rst_ctrl_0}]

# IP: bd/design_1/ip/design_1_proc_sys_rst_vid_0/design_1_proc_sys_rst_vid_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_rst_vid_0 || ORIG_REF_NAME==design_1_proc_sys_rst_vid_0}]

# IP: bd/design_1/ip/design_1_proc_sys_rst_vid1_0/design_1_proc_sys_rst_vid1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_rst_vid1_0 || ORIG_REF_NAME==design_1_proc_sys_rst_vid1_0}]

# IP: bd/design_1/ip/design_1_axi_interconnect_1_0/design_1_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_1_0 || ORIG_REF_NAME==design_1_axi_interconnect_1_0}]

# IP: bd/design_1/ip/design_1_xbar_1/design_1_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_1 || ORIG_REF_NAME==design_1_xbar_1}]

# IP: bd/design_1/ip/design_1_axi_vdma_new_0/design_1_axi_vdma_new_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_new_0 || ORIG_REF_NAME==design_1_axi_vdma_new_0}]

# IP: bd/design_1/ip/design_1_fmc_imageon_hdmi_in_0_0/design_1_fmc_imageon_hdmi_in_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fmc_imageon_hdmi_in_0_0 || ORIG_REF_NAME==design_1_fmc_imageon_hdmi_in_0_0}]

# IP: bd/design_1/ip/design_1_net_gnd_0/design_1_net_gnd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_net_gnd_0 || ORIG_REF_NAME==design_1_net_gnd_0}]

# IP: bd/design_1/ip/design_1_net_vcc_0/design_1_net_vcc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_net_vcc_0 || ORIG_REF_NAME==design_1_net_vcc_0}]

# IP: bd/design_1/ip/design_1_v_vid_in_axi4s_1_0/design_1_v_vid_in_axi4s_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_vid_in_axi4s_1_0 || ORIG_REF_NAME==design_1_v_vid_in_axi4s_1_0}]

# IP: bd/design_1/ip/design_1_vtd_0/design_1_vtd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vtd_0 || ORIG_REF_NAME==design_1_vtd_0}]

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0}]

# IP: bd/design_1/ip/design_1_fmc_imageon_hdmi_out_0_0/design_1_fmc_imageon_hdmi_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fmc_imageon_hdmi_out_0_0 || ORIG_REF_NAME==design_1_fmc_imageon_hdmi_out_0_0}]

# IP: bd/design_1/ip/design_1_net_gnd_1/design_1_net_gnd_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_net_gnd_1 || ORIG_REF_NAME==design_1_net_gnd_1}]

# IP: bd/design_1/ip/design_1_net_vcc_1/design_1_net_vcc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_net_vcc_1 || ORIG_REF_NAME==design_1_net_vcc_1}]

# IP: bd/design_1/ip/design_1_v_axi4s_vid_out_1_0/design_1_v_axi4s_vid_out_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_axi4s_vid_out_1_0 || ORIG_REF_NAME==design_1_v_axi4s_vid_out_1_0}]

# IP: bd/design_1/ip/design_1_vtg_0/design_1_vtg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vtg_0 || ORIG_REF_NAME==design_1_vtg_0}]

# IP: bd/design_1/ip/design_1_axis_subset_converter_0_0/design_1_axis_subset_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_subset_converter_0_0 || ORIG_REF_NAME==design_1_axis_subset_converter_0_0}]

# IP: bd/design_1/ip/design_1_v_proc_ss_0_0/design_1_v_proc_ss_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_proc_ss_0_0 || ORIG_REF_NAME==design_1_v_proc_ss_0_0}]

# Block Designs: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/bd_0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0 || ORIG_REF_NAME==bd_0}]

# IP: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_0/bd_0_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_axi_interconnect_0_0 || ORIG_REF_NAME==bd_0_axi_interconnect_0_0}]

# IP: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_1/bd_0_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_xbar_0 || ORIG_REF_NAME==bd_0_xbar_0}]

# IP: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_2/bd_0_v_vscaler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_v_vscaler_0 || ORIG_REF_NAME==bd_0_v_vscaler_0}]

# IP: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_3/bd_0_v_hscaler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_v_hscaler_0 || ORIG_REF_NAME==bd_0_v_hscaler_0}]

# IP: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_4/bd_0_input_size_set_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_input_size_set_0 || ORIG_REF_NAME==bd_0_input_size_set_0}]

# IP: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_5/bd_0_rst_axis_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_rst_axis_0 || ORIG_REF_NAME==bd_0_rst_axis_0}]

# IP: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_6/bd_0_reset_sel_axis_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_reset_sel_axis_0 || ORIG_REF_NAME==bd_0_reset_sel_axis_0}]

# IP: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_7/bd_0_axis_register_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_axis_register_slice_0_0 || ORIG_REF_NAME==bd_0_axis_register_slice_0_0}]

# IP: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_8/bd_0_axis_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_axis_fifo_0 || ORIG_REF_NAME==bd_0_axis_fifo_0}]

# IP: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_9/bd_0_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_xlslice_0_0 || ORIG_REF_NAME==bd_0_xlslice_0_0}]

# IP: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_10/bd_0_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_xlslice_1_0 || ORIG_REF_NAME==bd_0_xlslice_1_0}]

# IP: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_11/bd_0_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_auto_cc_0 || ORIG_REF_NAME==bd_0_auto_cc_0}]

# IP: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_12/bd_0_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_auto_cc_1 || ORIG_REF_NAME==bd_0_auto_cc_1}]

# IP: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_13/bd_0_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_auto_cc_2 || ORIG_REF_NAME==bd_0_auto_cc_2}]

# IP: bd/design_1/ip/design_1_axis_subset_converter_1_3/design_1_axis_subset_converter_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_subset_converter_1_3 || ORIG_REF_NAME==design_1_axis_subset_converter_1_3}]

# IP: bd/design_1/ip/design_1_s00_regslice_0/design_1_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_0 || ORIG_REF_NAME==design_1_s00_regslice_0}]

# IP: bd/design_1/ip/design_1_s00_data_fifo_0/design_1_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_data_fifo_0 || ORIG_REF_NAME==design_1_s00_data_fifo_0}]

# IP: bd/design_1/ip/design_1_s01_regslice_0/design_1_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s01_regslice_0 || ORIG_REF_NAME==design_1_s01_regslice_0}]

# IP: bd/design_1/ip/design_1_m00_data_fifo_0/design_1_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m00_data_fifo_0 || ORIG_REF_NAME==design_1_m00_data_fifo_0}]

# IP: bd/design_1/ip/design_1_m00_regslice_0/design_1_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m00_regslice_0 || ORIG_REF_NAME==design_1_m00_regslice_0}]

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0}]

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1}]

# IP: bd/design_1/ip/design_1_auto_us_cc_df_0/design_1_auto_us_cc_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_cc_df_0 || ORIG_REF_NAME==design_1_auto_us_cc_df_0}]

# XDC: bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_iic_0_0 || ORIG_REF_NAME==design_1_axi_iic_0_0}]

# XDC: bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_proc_sys_rst_ctrl_0/design_1_proc_sys_rst_ctrl_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_rst_ctrl_0 || ORIG_REF_NAME==design_1_proc_sys_rst_ctrl_0}]

# XDC: bd/design_1/ip/design_1_proc_sys_rst_ctrl_0/design_1_proc_sys_rst_ctrl_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_rst_ctrl_0 || ORIG_REF_NAME==design_1_proc_sys_rst_ctrl_0}]

# XDC: bd/design_1/ip/design_1_proc_sys_rst_ctrl_0/design_1_proc_sys_rst_ctrl_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_proc_sys_rst_vid_0/design_1_proc_sys_rst_vid_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_rst_vid_0 || ORIG_REF_NAME==design_1_proc_sys_rst_vid_0}]

# XDC: bd/design_1/ip/design_1_proc_sys_rst_vid_0/design_1_proc_sys_rst_vid_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_rst_vid_0 || ORIG_REF_NAME==design_1_proc_sys_rst_vid_0}]

# XDC: bd/design_1/ip/design_1_proc_sys_rst_vid_0/design_1_proc_sys_rst_vid_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_proc_sys_rst_vid1_0/design_1_proc_sys_rst_vid1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_rst_vid1_0 || ORIG_REF_NAME==design_1_proc_sys_rst_vid1_0}]

# XDC: bd/design_1/ip/design_1_proc_sys_rst_vid1_0/design_1_proc_sys_rst_vid1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_rst_vid1_0 || ORIG_REF_NAME==design_1_proc_sys_rst_vid1_0}]

# XDC: bd/design_1/ip/design_1_proc_sys_rst_vid1_0/design_1_proc_sys_rst_vid1_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_vdma_new_0/design_1_axi_vdma_new_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_new_0 || ORIG_REF_NAME==design_1_axi_vdma_new_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_vdma_new_0/design_1_axi_vdma_new_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_new_0 || ORIG_REF_NAME==design_1_axi_vdma_new_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_vdma_new_0/design_1_axi_vdma_new_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_v_vid_in_axi4s_1_0/design_1_v_vid_in_axi4s_1_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_v_vid_in_axi4s_1_0 || ORIG_REF_NAME==design_1_v_vid_in_axi4s_1_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_v_vid_in_axi4s_1_0/design_1_v_vid_in_axi4s_1_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_vtd_0/design_1_vtd_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_vtd_0 || ORIG_REF_NAME==design_1_vtd_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_vtd_0/design_1_vtd_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_v_axi4s_vid_out_1_0/design_1_v_axi4s_vid_out_1_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_v_axi4s_vid_out_1_0 || ORIG_REF_NAME==design_1_v_axi4s_vid_out_1_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_v_axi4s_vid_out_1_0/design_1_v_axi4s_vid_out_1_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_vtg_0/design_1_vtg_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_vtg_0 || ORIG_REF_NAME==design_1_vtg_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_vtg_0/design_1_vtg_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axis_subset_converter_0_0/design_1_axis_subset_converter_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_1/bd_0_xbar_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_2/bd_0_v_vscaler_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_v_vscaler_0 || ORIG_REF_NAME==bd_0_v_vscaler_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_2/bd_0_v_vscaler_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_3/bd_0_v_hscaler_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_v_hscaler_0 || ORIG_REF_NAME==bd_0_v_hscaler_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_3/bd_0_v_hscaler_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_4/bd_0_input_size_set_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_5/bd_0_rst_axis_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_rst_axis_0 || ORIG_REF_NAME==bd_0_rst_axis_0}]

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_5/bd_0_rst_axis_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_rst_axis_0 || ORIG_REF_NAME==bd_0_rst_axis_0}]

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_5/bd_0_rst_axis_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_6/bd_0_reset_sel_axis_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_reset_sel_axis_0 || ORIG_REF_NAME==bd_0_reset_sel_axis_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_6/bd_0_reset_sel_axis_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_6/bd_0_reset_sel_axis_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_reset_sel_axis_0 || ORIG_REF_NAME==bd_0_reset_sel_axis_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_7/bd_0_axis_register_slice_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_8/bd_0_axis_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_8/bd_0_axis_fifo_0/bd_0_axis_fifo_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_axis_fifo_0 || ORIG_REF_NAME==bd_0_axis_fifo_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_11/bd_0_auto_cc_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_11/bd_0_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_auto_cc_0 || ORIG_REF_NAME==bd_0_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_12/bd_0_auto_cc_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_12/bd_0_auto_cc_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_auto_cc_1 || ORIG_REF_NAME==bd_0_auto_cc_1}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_13/bd_0_auto_cc_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_13/bd_0_auto_cc_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_auto_cc_2 || ORIG_REF_NAME==bd_0_auto_cc_2}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/bd_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_v_proc_ss_0_0/design_1_v_proc_ss_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axis_subset_converter_1_3/design_1_axis_subset_converter_1_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_s00_regslice_0/design_1_s00_regslice_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_s00_data_fifo_0/design_1_s00_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_s01_regslice_0/design_1_s01_regslice_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_m00_data_fifo_0/design_1_m00_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_m00_regslice_0/design_1_m00_regslice_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_us_cc_df_0/design_1_auto_us_cc_df_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_us_cc_df_0/design_1_auto_us_cc_df_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_cc_df_0 || ORIG_REF_NAME==design_1_auto_us_cc_df_0}] {/inst }]/inst ]]

# XDC: bd/design_1/design_1_ooc.xdc
