# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.cache/wt [current_project]
set_property parent.project_path C:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.2 [current_project]
set_property ip_repo_paths c:/hdmi_final/HW/hw_lib [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files C:/hdmi_final/HW/rtl/design_1_scaler_old_0.coe
add_files C:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_rst_ctrl_0/design_1_proc_sys_rst_ctrl_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_rst_ctrl_0/design_1_proc_sys_rst_ctrl_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_rst_ctrl_0/design_1_proc_sys_rst_ctrl_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_rst_vid_0/design_1_proc_sys_rst_vid_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_rst_vid_0/design_1_proc_sys_rst_vid_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_rst_vid_0/design_1_proc_sys_rst_vid_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_rst_vid1_0/design_1_proc_sys_rst_vid1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_rst_vid1_0/design_1_proc_sys_rst_vid1_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_rst_vid1_0/design_1_proc_sys_rst_vid1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_new_0/design_1_axi_vdma_new_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_new_0/design_1_axi_vdma_new_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_new_0/design_1_axi_vdma_new_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_1_0/design_1_v_vid_in_axi4s_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_1_0/design_1_v_vid_in_axi4s_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_vtd_0/design_1_vtd_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_vtd_0/design_1_vtd_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_axi4s_vid_out_1_0/design_1_v_axi4s_vid_out_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_axi4s_vid_out_1_0/design_1_v_axi4s_vid_out_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_vtg_0/design_1_vtg_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_vtg_0/design_1_vtg_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axis_subset_converter_0_0/design_1_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_1/bd_0_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_2/bd_0_v_vscaler_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_2/bd_0_v_vscaler_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_3/bd_0_v_hscaler_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_3/bd_0_v_hscaler_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_4/bd_0_input_size_set_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_5/bd_0_rst_axis_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_5/bd_0_rst_axis_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_5/bd_0_rst_axis_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_6/bd_0_reset_sel_axis_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_6/bd_0_reset_sel_axis_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_6/bd_0_reset_sel_axis_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_7/bd_0_axis_register_slice_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_8/bd_0_axis_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_8/bd_0_axis_fifo_0/bd_0_axis_fifo_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_11/bd_0_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_11/bd_0_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_12/bd_0_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_12/bd_0_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_13/bd_0_auto_cc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_13/bd_0_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/bd_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/design_1_v_proc_ss_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axis_subset_converter_1_3/design_1_axis_subset_converter_1_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_s00_regslice_0/design_1_s00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_s00_data_fifo_0/design_1_s00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_s01_regslice_0/design_1_s01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_m00_data_fifo_0/design_1_m00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_m00_regslice_0/design_1_m00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_auto_us_cc_df_0/design_1_auto_us_cc_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/ip/design_1_auto_us_cc_df_0/design_1_auto_us_cc_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all C:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files C:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib {
  C:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
  C:/hdmi_final/HW/rtl/scaler_to_vpss.v
}
read_xdc C:/hdmi_final/HW/xdc/scaler_to_vpss_timing.xdc
set_property used_in_implementation false [get_files C:/hdmi_final/HW/xdc/scaler_to_vpss_timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
compile_c [get_files C:/hdmi_final/HW/proj/scaler_to_vpss_v1_0/scaler_to_vpss_v1_0.srcs/sources_1/bd/design_1/design_1.bd
]
synth_design -top scaler_to_vpss -part xc7z020clg484-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
write_checkpoint -noxdef scaler_to_vpss.dcp
catch { report_utilization -file scaler_to_vpss_utilization_synth.rpt -pb scaler_to_vpss_utilization_synth.pb }
